// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjSywdyapLKoGYg-gGk1k8LkUeY20z3QE',
    appId: '1:143399248318:web:6655b8a5c35472033c19ef',
    messagingSenderId: '143399248318',
    projectId: 'health-app-76faf',
    authDomain: 'health-app-76faf.firebaseapp.com',
    storageBucket: 'health-app-76faf.appspot.com',
    measurementId: 'G-WZ6XD96ZHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6rBNgfK2jGbFYumtGExfbxgjUQMqOzsE',
    appId: '1:143399248318:android:20b880eb7aaf332a3c19ef',
    messagingSenderId: '143399248318',
    projectId: 'health-app-76faf',
    storageBucket: 'health-app-76faf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB915LmjBYe9AfKUEEdFM8xLVZBkjT4PrE',
    appId: '1:143399248318:ios:7c342a3b40bde4923c19ef',
    messagingSenderId: '143399248318',
    projectId: 'health-app-76faf',
    storageBucket: 'health-app-76faf.appspot.com',
    iosClientId: '143399248318-th2so3l94phoncph6ovp4luurc4pqt83.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB915LmjBYe9AfKUEEdFM8xLVZBkjT4PrE',
    appId: '1:143399248318:ios:7c342a3b40bde4923c19ef',
    messagingSenderId: '143399248318',
    projectId: 'health-app-76faf',
    storageBucket: 'health-app-76faf.appspot.com',
    iosClientId: '143399248318-th2so3l94phoncph6ovp4luurc4pqt83.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthApp',
  );
}
